// Auto-generated. Do not edit!

// (in-package action_example.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountdownGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_number = null;
      this.target_step = null;
    }
    else {
      if (initObj.hasOwnProperty('target_number')) {
        this.target_number = initObj.target_number
      }
      else {
        this.target_number = 0;
      }
      if (initObj.hasOwnProperty('target_step')) {
        this.target_step = initObj.target_step
      }
      else {
        this.target_step = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountdownGoal
    // Serialize message field [target_number]
    bufferOffset = _serializer.int32(obj.target_number, buffer, bufferOffset);
    // Serialize message field [target_step]
    bufferOffset = _serializer.int32(obj.target_step, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountdownGoal
    let len;
    let data = new CountdownGoal(null);
    // Deserialize message field [target_number]
    data.target_number = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [target_step]
    data.target_step = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_example/CountdownGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f70b62431a53ca0ff987c03fd2dbcdf9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal define
    int32 target_number
    int32 target_step
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountdownGoal(null);
    if (msg.target_number !== undefined) {
      resolved.target_number = msg.target_number;
    }
    else {
      resolved.target_number = 0
    }

    if (msg.target_step !== undefined) {
      resolved.target_step = msg.target_step;
    }
    else {
      resolved.target_step = 0
    }

    return resolved;
    }
};

module.exports = CountdownGoal;
