// Auto-generated. Do not edit!

// (in-package action_example.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountdownFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.count_percent = null;
      this.count_current = null;
    }
    else {
      if (initObj.hasOwnProperty('count_percent')) {
        this.count_percent = initObj.count_percent
      }
      else {
        this.count_percent = 0.0;
      }
      if (initObj.hasOwnProperty('count_current')) {
        this.count_current = initObj.count_current
      }
      else {
        this.count_current = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountdownFeedback
    // Serialize message field [count_percent]
    bufferOffset = _serializer.float32(obj.count_percent, buffer, bufferOffset);
    // Serialize message field [count_current]
    bufferOffset = _serializer.int32(obj.count_current, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountdownFeedback
    let len;
    let data = new CountdownFeedback(null);
    // Deserialize message field [count_percent]
    data.count_percent = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [count_current]
    data.count_current = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_example/CountdownFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '939cc9132efdc6d2171ee36be1d52aab';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback define
    float32 count_percent
    int32   count_current
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountdownFeedback(null);
    if (msg.count_percent !== undefined) {
      resolved.count_percent = msg.count_percent;
    }
    else {
      resolved.count_percent = 0.0
    }

    if (msg.count_current !== undefined) {
      resolved.count_current = msg.count_current;
    }
    else {
      resolved.count_current = 0
    }

    return resolved;
    }
};

module.exports = CountdownFeedback;
