(cl:defpackage action_example-msg
  (:use )
  (:export
   "<COUNTDOWNACTION>"
   "COUNTDOWNACTION"
   "<COUNTDOWNACTIONFEEDBACK>"
   "COUNTDOWNACTIONFEEDBACK"
   "<COUNTDOWNACTIONGOAL>"
   "COUNTDOWNACTIONGOAL"
   "<COUNTDOWNACTIONRESULT>"
   "COUNTDOWNACTIONRESULT"
   "<COUNTDOWNFEEDBACK>"
   "COUNTDOWNFEEDBACK"
   "<COUNTDOWNGOAL>"
   "COUNTDOWNGOAL"
   "<COUNTDOWNRESULT>"
   "COUNTDOWNRESULT"
  ))

