; Auto-generated. Do not edit!


(cl:in-package action_example-msg)


;//! \htmlinclude CountdownFeedback.msg.html

(cl:defclass <CountdownFeedback> (roslisp-msg-protocol:ros-message)
  ((count_percent
    :reader count_percent
    :initarg :count_percent
    :type cl:float
    :initform 0.0)
   (count_current
    :reader count_current
    :initarg :count_current
    :type cl:integer
    :initform 0))
)

(cl:defclass CountdownFeedback (<CountdownFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountdownFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountdownFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_example-msg:<CountdownFeedback> is deprecated: use action_example-msg:CountdownFeedback instead.")))

(cl:ensure-generic-function 'count_percent-val :lambda-list '(m))
(cl:defmethod count_percent-val ((m <CountdownFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_example-msg:count_percent-val is deprecated.  Use action_example-msg:count_percent instead.")
  (count_percent m))

(cl:ensure-generic-function 'count_current-val :lambda-list '(m))
(cl:defmethod count_current-val ((m <CountdownFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_example-msg:count_current-val is deprecated.  Use action_example-msg:count_current instead.")
  (count_current m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountdownFeedback>) ostream)
  "Serializes a message object of type '<CountdownFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'count_percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let* ((signed (cl:slot-value msg 'count_current)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountdownFeedback>) istream)
  "Deserializes a message object of type '<CountdownFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'count_percent) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'count_current) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountdownFeedback>)))
  "Returns string type for a message object of type '<CountdownFeedback>"
  "action_example/CountdownFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountdownFeedback)))
  "Returns string type for a message object of type 'CountdownFeedback"
  "action_example/CountdownFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountdownFeedback>)))
  "Returns md5sum for a message object of type '<CountdownFeedback>"
  "939cc9132efdc6d2171ee36be1d52aab")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountdownFeedback)))
  "Returns md5sum for a message object of type 'CountdownFeedback"
  "939cc9132efdc6d2171ee36be1d52aab")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountdownFeedback>)))
  "Returns full string definition for message of type '<CountdownFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback define~%float32 count_percent~%int32   count_current~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountdownFeedback)))
  "Returns full string definition for message of type 'CountdownFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback define~%float32 count_percent~%int32   count_current~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountdownFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountdownFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CountdownFeedback
    (cl:cons ':count_percent (count_percent msg))
    (cl:cons ':count_current (count_current msg))
))
