; Auto-generated. Do not edit!


(cl:in-package action_example-msg)


;//! \htmlinclude CountdownGoal.msg.html

(cl:defclass <CountdownGoal> (roslisp-msg-protocol:ros-message)
  ((target_number
    :reader target_number
    :initarg :target_number
    :type cl:integer
    :initform 0)
   (target_step
    :reader target_step
    :initarg :target_step
    :type cl:integer
    :initform 0))
)

(cl:defclass CountdownGoal (<CountdownGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountdownGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountdownGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_example-msg:<CountdownGoal> is deprecated: use action_example-msg:CountdownGoal instead.")))

(cl:ensure-generic-function 'target_number-val :lambda-list '(m))
(cl:defmethod target_number-val ((m <CountdownGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_example-msg:target_number-val is deprecated.  Use action_example-msg:target_number instead.")
  (target_number m))

(cl:ensure-generic-function 'target_step-val :lambda-list '(m))
(cl:defmethod target_step-val ((m <CountdownGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_example-msg:target_step-val is deprecated.  Use action_example-msg:target_step instead.")
  (target_step m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountdownGoal>) ostream)
  "Serializes a message object of type '<CountdownGoal>"
  (cl:let* ((signed (cl:slot-value msg 'target_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'target_step)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountdownGoal>) istream)
  "Deserializes a message object of type '<CountdownGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_step) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountdownGoal>)))
  "Returns string type for a message object of type '<CountdownGoal>"
  "action_example/CountdownGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountdownGoal)))
  "Returns string type for a message object of type 'CountdownGoal"
  "action_example/CountdownGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountdownGoal>)))
  "Returns md5sum for a message object of type '<CountdownGoal>"
  "f70b62431a53ca0ff987c03fd2dbcdf9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountdownGoal)))
  "Returns md5sum for a message object of type 'CountdownGoal"
  "f70b62431a53ca0ff987c03fd2dbcdf9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountdownGoal>)))
  "Returns full string definition for message of type '<CountdownGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal define~%int32 target_number~%int32 target_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountdownGoal)))
  "Returns full string definition for message of type 'CountdownGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal define~%int32 target_number~%int32 target_step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountdownGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountdownGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CountdownGoal
    (cl:cons ':target_number (target_number msg))
    (cl:cons ':target_step (target_step msg))
))
